테스트 실패 시 에러 로그 추가

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -24,5 +24,4 @@ jobs:
       uses: gradle/actions/setup-gradle@v4.0.0
 
     - name: Run tests with Gradle
-      run: ./gradlew test
-      
+      run: ./gradlew test || (echo "::error::Test Failed" && exit 1)
